### ISSUE TITLE
Linux build instructions?

### ISSUE THREAD

**Issue by znmeb** [bwhitman/tulipcc#111]
I can probably help out with this. I might even be able to get it running on Windows via Windows Subsystem for Linux, but I can't make any guarantees about audio performance or USB connectivity.

**Comment by bwhitman** [comment]
That would be great. Keyboard input is handled by SDL on Desktop builds so it should just work if you get that going.

**Comment by znmeb** [comment]
I took a look at the macOS Makefile yesterday - it looks very Mac-specific, I'm looking into some more generic build configuration tools like CMake, unless there's something simpler that will work. CMake would in theory give you a single source tree that would build on Linux, Windows and Mac. But I don't own a Mac so I couldn't test that part.

**Comment by bwhitman** [comment]
For a head start on a linux build of Tulip Desktop, i'd look at the [`unix` Makefile in Micropython](https://github.com/micropython/micropython/blob/master/ports/unix/Makefile)

**Comment by znmeb** [comment]
> For a head start on a linux build of Tulip Desktop, i'd look at the [`unix` Makefile in Micropython](https://github.com/micropython/micropython/blob/master/ports/unix/Makefile)

It would be faster for me to buy a Mac Mini, a keyboard and a display than to learn the MicroPython build configuration process.

**Comment by bwhitman** [comment]
We have updated [the Tulip Desktop page](https://github.com/bwhitman/tulipcc/blob/main/docs/tulip_desktop.md) with instructions on how to build on Linux. Haven't tested it beyond my Ubuntu 22 VM. Give it a go and we can follow up with any more issues!
