### ISSUE TITLE
How to transfer files between pc and tulipcc?

### ISSUE THREAD

**Issue by jd3096-mpy** [bwhitman/tulipcc#188]
Is there a way to ransfer files between pc and tulipcc？I can't found it in WIKI.
I use tulipcc on T-deck.
Thanks.

**Comment by bwhitman** [comment]
a few ways:
 - For both directions: use Tulip world from Tulip Desktop: just `world.upload(file)` and `world.download(file)` should work once you're on wifi. Note that this will make your files public for anyone else on Tulip to see
 - For computer to Tulip privately: run a small web server on your computer and use `tulip.url_save(url, filename)` on Tulip. I just use python: `python3 -m http.server`, which creates a web server of the current directory from port 8000 of localhost. 
 - From Tulip to computer privately: there's nothing "easy" for this. You can write one yourself in Python on tulip using the `requests` library. For example, you can use github gist API https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28#create-a-gist or run something on your web server and have Tulip POST or PUT the file to it. There's also the Micropython WebREPL: https://github.com/micropython/webrepl?tab=readme-ov-file which could work on Tulip but we do not include it with Tulip itself.
