### ISSUE TITLE
Voices does not stop sequencer on exit

### ISSUE THREAD

**Issue by drepetto** [bwhitman/tulipcc#216]
If I run Voices from the menu and turn on the arrpegiator and the hold, play some notes, then quit, the sequencer continues playing the notes after quitting. If I then do tulip.seq_stop() there's often a stuck note remaining after the sequencer stops.

**Comment by drepetto** [comment]
It occurs to me that maybe this is the desired behavior -- maybe it's more an issue of we haven't quite defined what an App is on Tulip?

**Comment by bwhitman** [comment]
i agree the voices sequencer (for arpeg) should only run when voices is running. We'll fix that!

**Comment by bwhitman** [comment]
moved to chores in #208
