### ISSUE TITLE
desktop tulip crashes drawing shapes with zero or negative coordinates

### ISSUE THREAD

**Issue by drepetto** [bwhitman/tulipcc#56]
this will crash the desktop app:

>>>tulip.circle(0,0,5,1,1)

any coordinate <= 0 crashes

**Comment by drepetto** [comment]
Ooops, I think this is a duplicate of:
https://github.com/bwhitman/tulipcc/issues/30#issue-1625221944

**Comment by bwhitman** [comment]
Yeah, same thing. We should fix this soon! Thank you
