### ISSUE TITLE
shapes with parts offscreen are drawn elsewhere

### ISSUE THREAD

**Issue by drepetto** [bwhitman/tulipcc#57]
tulip.circle(4,400,10,10,1) will draw part of the circle where expected but the part offscreen will be drawn elsewhere on screen.

**Comment by bwhitman** [comment]
Ooh, interesting. I think we just not draw things in the `bresenham.c` collection outside of the screen (or offscreen). We can still let people do it but just not emit pixels on bits that are not in our screen area.  This is related to but different than #30

**Comment by bwhitman** [comment]
We now emit any pixels off `H_RES+OFFSCREEN_X_PX` or `V_RES+OFFSCREEN_Y_PX`. `bresenham.c` can draw offscreen fine but will not "wrap around" anymore to unexpected places.
