### ISSUE TITLE
update documentation on Alles vs Tulip Alles

### ISSUE THREAD

**Issue by drepetto** [bwhitman/tulipcc#63]
This alles example crashes Tulip desktop on MacOS:
alles.send(wave=alles.PCM,vel=1,patch=35,feedback=1) # nice violin

It also crashes on any other patch >= 35

In addition, patches 29-34 are silent (but don't crash). Lower numbered patches work fine. 

MacOS 12.6.5
Tulip OS 8252daaf-dirty on 2023-05-04

**Comment by bwhitman** [comment]
Tulip uses the smaller set of PCM samples. I think there's only 29. It'd be great to document the changes between e.g Alles and Tulip somewhere, including the new @dpwe stuff
