### ISSUE TITLE
esp32s3/usb_keyboard: KeyboardTimer

### ISSUE THREAD

**Issue by dpwe** [bwhitman/tulipcc#77]
I don't (yet) understand the USB code, but this looks suspect:
https://github.com/bwhitman/tulipcc/blob/main/ports/esp32s3/usb_keyboard.c#L312

At the top of the `while(1)`  loop, `KeyboardTimer` gets set to the current esp32 system time in ms, but then in this clause (which appears to poll the keyboard by issuing `usb_host_transfer_submit`), `KeyboardTimer` gets set to zero. It is also part of a condition for entering the block.

I don't know what `KeyboardInterval` (from `endpoint->bInterval`) is supposed to be, but it looks like it's a minimum period between polling requests.  In which case, shouldn't the entry condition be 
```(KeyboardTimer - last_poll_time_ms) > KeyboardInterval```
and the reset in the block should be
```last_poll_time_ms = KeyboardTimer```
?

I think the result of this is that keyboard polling will be saturated, i.e. immediately `isKeyboardPolling` is cleared in `keyboard_transfer_cb`, another poll request will be issued.

**Comment by bwhitman** [comment]
Yeah, you can see I screwed that up by putting the key repeat stuff in there. The original was

https://github.com/touchgadget/esp32-usb-host-demos/blob/e3dbeefa84d6ddea9586efa6862d14c50af7916f/examples/usbhhidboot/usbhhidboot.ino#L169
