### ISSUE TITLE
PCM sound gets crunchy after playing lots of samples

### ISSUE THREAD

**Issue by drepetto** [bwhitman/tulipcc#81]
See bunny_bounce on tulip.world.

**Comment by bwhitman** [comment]
I am noticing this here. i think our call chain from the MP task for AMY/Alles messages is slowing down things. I am wondering if we could instead send Alles a message over the TaskNotify bus to the Alles/AMY task. basically, like a local version of the udp_send code. I will do some more digging soon.

**Comment by bwhitman** [comment]
Will close this, i would bet this all works fine (and i'm not hearing any crackles in bunny_bounce). if it reappears we can re-visit.
